on: pull_request
name: Add label to PR
jobs:
  PR:
    name: PR opened filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PR opened filter
        uses: actions/bin/filter@master
        with:
          args: action opened
      - name: PR Labeler
        uses: TimonVS/pr-labeler@master
        needs: PR opened filter
        with:
          args: action opened
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
